# Generated by Django 2.2 on 2021-01-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210119_1858'),
        ('profiles', '0002_auto_20200108_2100'),
    ]

    operations = [
    ]
