# Generated by Django 2.2 on 2020-12-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20201203_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['id']},
        ),
    ]
