# Generated by Django 2.2 on 2021-01-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20210119_1736'),
        ('tweets', '0006_auto_20200108_2040'),
    ]

    operations = [
    ]
